name    'puppetlabs-stunnel'
version '0.0.1'
source  'git@github.com:puppetlabs/puppetlabs-stunnel.git'
author  'puppetlabs'
license 'Apache License 2.0'
summary 'Puppet Stunnel Module'
description 'Provides a defined resource type for managing stunnel on Debian and Red Hat systems.'
project_page 'https://github.com/puppetlabs/puppetlabs-stunnel'