name    'puppetlabs-stunnel'
version '0.0.1'
source 'https://github.com/puppetlabs/puppetlabs-stunnel.git'
author 'puppetlabs'
license 'Apache License, Version 2.0'
summary 'A module for creating secure tunnels'
description 'Uses the stunnel application to setup SSL encrypted and authenticated tunnels.'
project_page 'https://github.com/puppetlabs/puppetlabs-stunnel'
dependency 'puppetlabs/stdlib', '>= 2.3.1'
